

target 'Datasnap_Example' do
    pod 'Datasnap', :path => '../'
    
    target 'Datasnap_Tests' do
        inherit! :search_paths
        
        pod 'Kiwi'
        pod 'Gimbal'
        pod 'AFNetworking'
    end
end
